### ISSUE TITLE
Can't run japonicus

### ISSUE THREAD

**Issue by mrgithub** [Gab0/japonicus#82] opened 2018-02-18 11:15 UTC
I'm a noobie.  I've installed python3.6 and have gekko running ok.  Can't seem to run japonicus.

At the prompt I'm typing this (I wasn't sure what switches to use):  

`/usr/bin/python3.6 japonicus.py `

I get this:
```

Traceback (most recent call last):
  File "japonicus.py", line 12, in <module>
    from Settings import getSettings
  File "/home/jay/japonicus/Settings.py", line 3, in <module>
    import js2py
ModuleNotFoundError: No module named 'js2py'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "japonicus.py", line 12, in <module>
    from Settings import getSettings
  File "/home/jay/japonicus/Settings.py", line 3, in <module>
    import js2py
ModuleNotFoundError: No module named 'js2py'

```

So it seems js2py is missing perhaps so I tried:

`pip3 install js2py`

and got this:
```
Requirement already satisfied: js2py in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.5/dist-packages (from js2py)
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from js2py)
Requirement already satisfied: pyjsparser>=2.5.1 in /usr/local/lib/python3.5/dist-packages (from js2py)
Requirement already satisfied: pytz in /usr/local/lib/python3.5/dist-packages (from tzlocal>=1.2->js2py)

```

What command should I be running?

**Comment by Gab0** [comment] 2018-02-18 13:04
Hey it seems your `pip3` command is linked to your python3.5, so you should just need to `$sudo pip3.6 -r requirements.txt` to get everything on your python3.6. Cheers!

**Comment by mrgithub** [comment] 2018-02-18 16:25
I didn't have pip3.6 installed so I followed the ticked instructions here to get python3.6 and pip3.6 installed:
`https://stackoverflow.com/questions/42662104/how-to-install-pip-for-python-3-6-on-ubuntu-16-10/44254088#44254088`

Now when I run the command with and without the -r switch I get one of the two:
`$sudo`` pip3.6 -r requirements.txt

Usage:   
  pip <command> [options]

no such option: -r`
or
`$ sudo pip3.6 requirements.txt 
ERROR: unknown command "requirements.txt"
`

**Comment by Gab0** [comment] 2018-02-18 17:03
Sorry... i meant `$sudo pip3.6 install -r requirements.txt`
And you should run that on japonicus folder ofc.

**Comment by Gab0** [comment] 2018-02-19 01:13
Hey @mrgithub, thats an old bug. just `$git pull` this repo and it should work.

**Comment by mrgithub** [comment] 2018-02-19 01:52
It's upto date but I recieve that error.

`python3.6 japonicus.py -b
	GEKKO
     ██╗ █████╗ ██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗   ██╗███████╗
     ██║██╔══██╗██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║   ██║██╔════╝
     ██║███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║   ██║███████╗
██   ██║██╔══██║██╔═══╝ ██║   ██║██║╚██╗██║██║██║     ██║   ██║╚════██║
╚█████╔╝██║  ██║██║     ╚██████╔╝██║ ╚████║██║╚██████╗╚██████╔╝███████║
 ╚════╝ ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═════╝ ╚══════╝
								v0.33

The profits reported here are the profit beyond market price change;
	i.e. shown profit =  <backtest profit> - <market profit in evaluated candlestick period>;
Traceback (most recent call last):
  File "japonicus.py", line 108, in <module>
    import evolution_bayes
  File "/home/jay/japonicus/evolution_bayes.py", line 31, in <module>
    TargetParameters = getSettings()["strategies"][Strategy]
KeyError: None
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "japonicus.py", line 108, in <module>
    import evolution_bayes
  File "/home/jay/japonicus/evolution_bayes.py", line 31, in <module>
    TargetParameters = getSettings()["strategies"][Strategy]
KeyError: None
`

**Comment by mrgithub** [comment] 2018-02-19 17:45
I've copied to create apt-pkg and re-ran:

`python3.6 japonicus.py -b -r
	GEKKO
     ██╗ █████╗ ██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗   ██╗███████╗
     ██║██╔══██╗██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║   ██║██╔════╝
     ██║███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║   ██║███████╗
██   ██║██╔══██║██╔═══╝ ██║   ██║██║╚██╗██║██║██║     ██║   ██║╚════██║
╚█████╔╝██║  ██║██║     ╚██████╔╝██║ ╚████║██║╚██████╗╚██████╔╝███████║
 ╚════╝ ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═════╝ ╚══════╝
								v0.33

The profits reported here are the profit beyond market price change;
	i.e. shown profit =  <backtest profit> - <market profit in evaluated candlestick period>;
Traceback (most recent call last):
  File "japonicus.py", line 108, in <module>
    import evolution_bayes
  File "/home/jay/japonicus/evolution_bayes.py", line 31, in <module>
    TargetParameters = getSettings()["strategies"][Strategy]
KeyError: None
`

**Comment by mrgithub** [comment] 2018-02-24 05:14
@Gab0 any ideas?

**Comment by Gab0** [comment] 2018-02-24 13:24
@mrgithub from your last post... first run was really a bug, its fixed now. The second says exactly what the problem is: your candle data is too short. Import more candles.

**Closed** 2018-04-06 16:12 UTC
