### ISSUE TITLE
FileNotFoundError: File b'output\\evolution_gen.csv' does not exist

### ISSUE THREAD

**Issue by stamun8** [Gab0/japonicus#21] opened 2017-10-08 09:28 UTC
ST]
Traceback (most recent call last):
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\dash\dash.py", line 551, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\dash\dash.py", line 508, in add_context
    output_value = func(*args, **kwargs)
  File "c:\gekkoJaponicus-master\web.py", line 103, in update_graph
    df = load_evolution_logs()
  File "c:\gekkoJaponicus-master\web.py", line 23, in load_evolution_logs
    df = pd.read_csv(filename, names=columns)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\pandas\io\parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\pandas\io\parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\pandas\io\parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\pandas\io\parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\site-packages
\pandas\io\parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 394, in pandas._libs.parsers.TextReader.
__cinit__ (pandas\_libs\parsers.c:4209)
  File "pandas\_libs\parsers.pyx", line 710, in pandas._libs.parsers.TextReader.
_setup_parser_source (pandas\_libs\parsers.c:8873)
FileNotFoundError: File b'output\\evolution_gen.csv' does not exist
127.0.0.1 - - [08/Oct/2017 12:27:14] "POST /_dash-update-component HTTP/1.1" 500
 -

**Comment by Gab0** [comment] 2017-10-08 13:07
This error is probably gone on the recent update. BTW, were you using -g or -b evolution method?
Thanks for the report.

**Comment by stamun8** [comment] 2017-10-09 16:42
still no success... Do you have any Virtual Machine image where it's running?

**Comment by stamun8** [comment] 2017-10-09 16:58
File "C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\lib\random.py", l
ine 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop,
 width))
ValueError: empty range for randrange() (1499621340,1498127341, -1493999)

**Comment by Gab0** [comment] 2017-10-09 21:49
@stamun8  On this randrange() error: you didn't provide the full traceback, right?
But doing some investigations I realized that randrange with [ step] option like `randrange(x,y,z)` doesn't appear on japonicus, so I'm just lost here.
At least, can you confirm the fail on '.csv' file not being found doesn't happen anymore?

Anyway I made a change that might be the solution for that `randrange` stuff. Please try it.. If it happens again, send full traceback man x]
I don't have the VM image but will try it on Amazon AWS soon.. thanks.

**Comment by xteejx** [comment] 2017-12-31 03:09
I can confirm this issue still exists on Ubuntu 16.04 with python 3.6.
Output:

127.0.0.1 - - [31/Dec/2017 03:05:28] "POST /_dash-update-component HTTP/1.1" 500 -
['/home/xxx/gekko/strategies/japonicus/ja354LRCRSI.js']
Creating strategy /home/xxx/gekko/strategies/japonicus/ja354DEMARSI.js file.
['/home/xxx/gekko/strategies/japonicus/ja354PPORSI.js']
Creating strategy /home/xxx/gekko/strategies/japonicus/ja354CCIRSI.js file.
127.0.0.1 - - [31/Dec/2017 03:05:43] "POST /_dash-update-component HTTP/1.1" 200 -
Loading
Loading
[2017-12-31 03:05:43,938] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/dash/dash.py", line 551, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/usr/local/lib/python3.6/dist-packages/dash/dash.py", line 508, in add_context
    output_value = func(*args, **kwargs)
  File "/home/xxx/gekkoJaponicus/web.py", line 145, in updateGraphs
    app.GraphicList[F].__setattr__('figure', update_graph(app.GraphicList[F].id))
  File "/home/xxx/gekkoJaponicus/web.py", line 30, in update_graph
    df = load_evolution_logs(filename="evolution_gen_Locale%s.csv" % ''.join(ID))
  File "/home/xxx/gekkoJaponicus/web.py", line 24, in load_evolution_logs
    df = pd.read_csv(filename, names=columns)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'output/evolution_gen_Locale2.csv' does not exist

**Comment by xteejx** [comment] 2017-12-31 03:14
This may be something to do with promoterz/statistics.py:60
>     LOGPATH ="output/evolution_gen_%s.csv" % locale.name

Not sure what locale is required for, but I'm en_GB here.
If graphs are drawn from the logfiles, then that's likely where the problem is as I'm not seeing them in the dash in my browser.

**Comment by xteejx** [comment] 2017-12-31 03:23
Okay, narrowed it down. When the browser is open with the -w option, this is when it happens. Running without is fine in the terminal.

**Comment by andr0s** [comment] 2018-01-16 21:43
Just hit the same issue. No fix yet?

**Comment by Gab0** [comment] 2018-01-16 22:53
@xteejx @andr0s @stamun8 Original thread error is a inofensive thing showing when the graphs try to update on data that doesn't exist yet. That happens during EPOCH zero. Yeah its a scary thing and will be fixed but got no consequences on program workx.
@stamun8 empty randrange stuff -> see #50, just got fixed.

**Closed by Gab0** 2018-01-16 22:53 UTC
